version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  # Optionnel: un outil pour visualiser la base de données, comme Adminer
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  postgres_data: