# Ce workflow construit un projet Java avec Maven et exécute les tests unitaires
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - uses: actions/checkout@v4

    # Étape 2 : Configurer le JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'            # Version du JDK
        distribution: 'temurin'       # Distribution OpenJDK
        cache: maven                  # Mise en cache des dépendances Maven

    # Étape 3 : Construire le projet et exécuter les tests
    - name: Build and Test with Maven
      run: mvn -B clean verify --file pom.xml
      # clean : Nettoie les anciens fichiers générés.
      # verify : Compile, teste, et vérifie le projet.

    # Étape 4 : Publier les résultats des tests JUnit
    - name: Publish test results
      if: always()                    # Publier les résultats même en cas d'échec des tests
      uses: actions/upload-artifact@v3
      with:
        name: junit-test-results
        path: target/surefire-reports/*.xml
        # Les rapports de test générés par Maven Surefire se trouvent ici par défaut.

